version: '3.9'

services:
    # Nginx-proxy service
    proxy-service:
        container_name: symfony-proxy
        image: jwilder/nginx-proxy
        ports:
            - '80:80'
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
            - php-service
        networks:
            - reverse_proxy

    # Nginx service
    nginx-service:
        container_name: symfony-nginx
        build:
            context: ./image/nginx
            args:
                NGINX_VERSION: ${NGINX_VERSION}
                DOMAIN_NAME: ${DOMAIN_NAME}
        environment:
            - VIRTUAL_HOST=${DOMAIN_NAME}
        depends_on:
            - php-service
        volumes:
            - ../public:/app
        networks:
            reverse_proxy:
            project_net:
            main:
                aliases:
                    - ${DOMAIN_NAME}

    # PHP-FPM service
    php-service:
        container_name: symfony-app
        build:
            context: ./image/php
            args:
                PHP_VERSION: ${PHP_VERSION}
                USER_APP: ${USER_APP}
                GROUP_APP: ${GROUP_APP}
                UID: ${UID}
                GID: ${GID}
        depends_on:
            - database-service
            - rabbitmq-service
        user: ${UID}:${GID}
        volumes:
            - ../:/app
        networks:
            - project_net

    # Postgres service
    database-service:
        container_name: symfony-postgres
        image: postgres:${POSTGRES_VERSION}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        user: ${UID}:${GID}
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - '49153:5432'
        networks:
            - project_net

    # RabbitMQ service
    rabbitmq-service:
        container_name: symfony-rabbitmq
        image: heidiks/rabbitmq-delayed-message-exchange:latest
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        user: ${UID}:${GID}
        volumes:
            - ./data/rabbitmq:/var/lib/rabbitmq
        ports:
            - '49154:15672'
        networks:
            - project_net

# Docker networks
networks:
    reverse_proxy:
    project_net:
        driver: bridge
    main:
        driver: bridge
